apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ebpf-runners
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: rashraj/eBPF-Security-CI-CD-Agent
      labels:
        - self-hosted
        - kubernetes
      env:
        - name: GITHUB_URL
          value: https://github.com
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: RUNNER_FEATURE_FLAG_ONCE
          value: "true"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_OPTIONS
          value: --tls-min-v1.0
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ebpf-runners-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: ebpf-runners
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    scaleUpThreshold: '1'
    scaleDownThreshold: '0'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
