# Updated runner values with container images and reduced resources for M1 Mac
githubConfigUrl: "https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}"
githubConfigSecret:
  github_token: "${GITHUB_TOKEN}"

# Runner labels
labels:
  - self-hosted
  - kubernetes
  - harphies

# Docker-in-Docker configuration with images specified
containerMode:
  type: dind

# Add container images with reduced resource requirements
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
          - name: GITHUB_URL
            value: https://github.com
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
          - name: RUNNER_FEATURE_FLAG_ONCE
            value: "true"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: NODE_OPTIONS
            value: --tls-min-v1.0
    initContainers:
      - name: init-dind-externals
        image: ghcr.io/actions/actions-runner:latest
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"