githubConfigUrl: "https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}"

githubConfigSecret:
  github_token: "${GITHUB_TOKEN}"

maxRunners: 5
minRunners: 1

template:
  spec:
    containers:
      # Main runner container
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_PTRACE
              - IPC_LOCK
              - NET_ADMIN
              - SYS_RESOURCE
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "2Gi"
        volumeMounts:
          - name: bpf-fs
            mountPath: /sys/fs/bpf
          - name: cgroup-fs
            mountPath: /sys/fs/cgroup
          - name: modules-fs
            mountPath: /lib/modules
            readOnly: true
          - name: debugfs
            mountPath: /sys/kernel/debug
          - name: tracefs
            mountPath: /sys/kernel/tracing
          - name: shared-tmp
            mountPath: /tmp
      
      - name: kntrl-sidecar
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Install dependencies
            apt-get update && apt-get install -y wget curl sudo
            
            # Download kntrl
            wget -q https://github.com/kondukto-io/kntrl/releases/download/v0.1.3/kntrl
            chmod +x kntrl
            
            # Create bundle directory structure for OPA
            mkdir -p /bundle/kntrl/network
            
            # Copy policies from ConfigMap mount
            cp /policies/*.rego /bundle/kntrl/network/
            
            # Set kernel parameters
            sysctl -w kernel.unprivileged_bpf_disabled=0 || true
            
            # Start kntrl with policy directory
            ./kntrl start --mode=trace \
              --output-file-name=/tmp/kntrl_report.out \
              --bundle-dir=/bundle \
              --verbose
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_PTRACE
              - IPC_LOCK
              - NET_ADMIN
              - SYS_RESOURCE
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"
        volumeMounts:
          - name: bpf-fs
            mountPath: /sys/fs/bpf
          - name: cgroup-fs
            mountPath: /sys/fs/cgroup
          - name: modules-fs
            mountPath: /lib/modules
            readOnly: true
          - name: debugfs
            mountPath: /sys/kernel/debug
          - name: tracefs
            mountPath: /sys/kernel/tracing
          - name: shared-tmp
            mountPath: /tmp
          - name: kntrl-policies
            mountPath: /policies
    
    securityContext:
      fsGroup: 1000
    
    volumes:
      - name: bpf-fs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: cgroup-fs
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: modules-fs
        hostPath:
          path: /lib/modules
          type: Directory
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
          type: Directory
      - name: tracefs
        hostPath:
          path: /sys/kernel/tracing
          type: Directory
      - name: shared-tmp
        emptyDir: {}
      - name: kntrl-policies
        configMap:
          name: kntrl-policies