# GitHub Actions Runner Scale Set Configuration for v0.11.0

# GitHub configuration
githubConfigUrl: "https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}"

# GitHub authentication - the script will replace this token placeholder
githubConfigSecret:
  github_token: "${GITHUB_TOKEN}"

# Runner labels that can be used in GitHub workflows
labels:
  - self-hosted
  - kubernetes
  - harphies

# Container mode configuration - Docker-in-Docker (dind)
containerMode:
  type: dind

# Runner pool size
minRunners: 1
maxRunners: 3

# The new listenerMetrics field that's required in v0.11.0
# If you don't need metrics, use an empty config
listenerMetrics:
  prometheus:
    enabled: false

# Runner pod template configuration
template:
  spec:
    containers:
      - name: runner
        env:
          - name: GITHUB_URL
            value: https://github.com
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
          - name: RUNNER_FEATURE_FLAG_ONCE
            value: "true"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: NODE_OPTIONS
            value: --tls-min-v1.0