apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ${RUNNER_NAME}
  namespace: ${RUNNER_NAMESPACE}
spec:
  replicas: 1
  template:
    spec:
      repository: ${GITHUB_OWNER}/${GITHUB_REPO}
      labels:
        - self-hosted
        - kubernetes
        - harphies
      env:
        - name: GITHUB_URL
          value: https://github.com
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: RUNNER_FEATURE_FLAG_ONCE
          value: "true"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_OPTIONS
          value: --tls-min-v1.0
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
      dockerEnabled: true
      dockerdWithinRunnerContainer: true
      ephemeral: false
      workDir: /tmp/runner
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 121  # Docker group
      workVolumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: work-dir
              mountPath: /tmp/runner
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: work-dir
          emptyDir: {}