apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ${RUNNER_NAME}-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: ${RUNNER_NAME}
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    scaleUpThreshold: '1'
    scaleDownThreshold: '0'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'