apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ${RUNNER_NAME}
  namespace: ${RUNNER_NAMESPACE}
spec:
  replicas: 2
  template:
    spec:
      repository: ${GITHUB_OWNER}/${GITHUB_REPO}
      labels:
        - self-hosted
        - kubernetes
        - harphies
      env:
        - name: GITHUB_URL
          value: https://github.com
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: RUNNER_FEATURE_FLAG_ONCE
          value: "true"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_OPTIONS
          value: --tls-min-v1.0
      containerMode: kubernetes
      dockerEnabled: true
      dockerdWithinRunnerContainer: true
      ephemeral: false
      workDir: /tmp/runner
      # Add the required workVolumeClaimTemplate with required storageClassName
      workVolumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
      # Define container details properly with security context
      containers:
        - name: runner
          securityContext:
            # Don't run as root (0)
            runAsUser: 1001
            runAsGroup: 121
            # Allow docker access but don't use privileged mode
            privileged: false
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock