gcloud container node-pools create ebpf-pool \
  --cluster=github-runners \
  --project=YOUR_PROJECT_ID \
  --region=europe-west4 \
  --machine-type=e2-standard-4 \
  --num-nodes=2 \
  --enable-autoscaling \
  --min-nodes=1 \
  --max-nodes=3 \
  --disk-size=50 \
  --image-type=UBUNTU_CONTAINERD \
  --system-config-from-file=sysctl-config.yaml