apiVersion: v1
kind: Pod
metadata:
  name: kntrl-fixed-test
  labels:
    app: kntrl-test
spec:
  containers:
  - name: kntrl-test-container
    image: ubuntu:22.04
    command: ["/bin/bash"]
    args: 
      - "-c"
      - |
        # Update and install dependencies
        echo "Installing dependencies..."
        apt-get update
        apt-get install -y curl wget sudo kmod procps

        # Mount debugfs and tracefs if not already mounted
        echo "Setting up kernel debug filesystem mounts..."
        if ! mount | grep -q "debugfs on /sys/kernel/debug"; then
          mkdir -p /sys/kernel/debug
          mount -t debugfs debugfs /sys/kernel/debug || echo "Failed to mount debugfs"
        fi
        
        if ! mount | grep -q "tracefs on /sys/kernel/tracing"; then
          mkdir -p /sys/kernel/tracing
          mount -t tracefs tracefs /sys/kernel/tracing || echo "Failed to mount tracefs"
        fi
        
        # Check mounts
        echo "Current mounts:"
        mount | grep -E 'debugfs|tracefs'
        
        # Show debugging filesystem contents
        echo "Debug filesystem contents:"
        ls -la /sys/kernel/debug || echo "Cannot access /sys/kernel/debug"
        ls -la /sys/kernel/tracing || echo "Cannot access /sys/kernel/tracing"
        
        # Download kntrl
        echo "Downloading kntrl..."
        wget -q https://github.com/kondukto-io/kntrl/releases/download/v0.1.3/kntrl 
        chmod +x kntrl
        
        # Start kntrl in trace mode with verbose output
        echo "Starting kntrl..."
        sudo ./kntrl start --mode=trace \
          --allowed-hosts=download.kondukto.io,docker.io,www.docker.com \
          --allow-github-meta=true \
          --verbose &
          
        # Wait for kntrl to initialize
        echo "Waiting for initialization..."
        sleep 5
        
        # Check if kntrl is running
        ps aux | grep kntrl
        
        # Run network tests
        echo "Testing domains:"
        echo "1. github.com (should be allowed):"
        curl -s -I https://github.com | head -1
        
        echo "2. google.com (should be blocked):"
        curl -s -I https://google.com | head -1
        
        echo "3. download.kondukto.io (should be allowed):"
        curl -s -I https://download.kondukto.io | head -1
        
        # Get kernel info
        echo "Kernel information:"
        uname -a
        
        echo "Kernel modules:"
        lsmod | grep -E 'bpf|trace' || echo "No relevant modules found"
        
        echo "BPF filesystem:"
        ls -la /sys/fs/bpf || echo "No BPF filesystem"
        
        # Keep the pod running for manual inspection
        echo "Tests completed. Pod will remain running for inspection."
        echo "You can connect to the pod with: kubectl exec -it kntrl-fixed-test -- bash"
        tail -f /dev/null
    securityContext:
      privileged: true  # Required for kntrl to access kernel features
    volumeMounts:
    - name: sys-kernel-debug
      mountPath: /sys/kernel/debug
    - name: sys-kernel-tracing
      mountPath: /sys/kernel/tracing
    - name: proc
      mountPath: /proc
    - name: sys-fs-bpf
      mountPath: /sys/fs/bpf
  volumes:
  - name: sys-kernel-debug
    hostPath:
      path: /sys/kernel/debug
      type: Directory
  - name: sys-kernel-tracing
    hostPath:
      path: /sys/kernel/tracing
      type: DirectoryOrCreate
  - name: proc
    hostPath:
      path: /proc
      type: Directory
  - name: sys-fs-bpf
    hostPath:
      path: /sys/fs/bpf
      type: DirectoryOrCreate
  restartPolicy: Never