name: Financial Reporting Service

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3
      
      - name: Secured Build
        run: |
          echo "Secure financial reporting service build on this runner"
          hostname
          env
          ls -la
  
  malicoius-build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3
      
      - name: Malicious Build
        run: |
          echo "Simulate malicious build trying to gain access to financial reporting service build on this runner and see how eBPF helps prevent and block that"
          hostname
          env
          ls -la