name: Financial Reporting Service

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3
      
      - name: Secured Build
        run: |
          echo "Secure financial reporting service build on this runner"
          hostname
          env
          ls -la  # This will list the files in your repository
  
  malicoius-build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3
      
      - name: Malicious Build
        run: |
          echo "Secure financial reporting service build on this runner"
          hostname
          env
          ls -la  # This will list the files in your repository