name: Financial Reporting Service

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3

      - name: Check Kernel Version
        run: uname -r

      - name: Download kntrl (arm64)
        run: |
          curl -L -o kntrl https://github.com/kondukto-io/kntrl/releases/download/v0.1.3/kntrl_arm64.arm64
          chmod +x kntrl
          sudo mv kntrl /usr/local/bin/kntrl

      - name: Secured Build
        run: |
          echo "Secure financial reporting service build on this runner"
          hostname
          env
          ls -la

      - name: kntrl agent (Monitor Mode - Binary - No Sudo Test)
        run: |
          echo "Starting kntrl agent in monitor mode (binary - no sudo)..."
          /usr/local/bin/kntrl run --mode=monitor --allowed-hosts=kondukto.io,${{ env.GITHUB_ACTIONS_URL }}
          echo "kntrl agent (no sudo) finished."
        continue-on-error: true

  malicious-build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3

      - name: Simulate Malicious Actions
        run: |
          echo "Simulating malicious build trying to gain access..."
          hostname
          env
          ls -la /etc/shadow # Attempt to access a sensitive file
          mkdir /tmp/evil_dir
          echo "Malicious file created" > /tmp/evil_dir/malicious.txt
          curl -m 10 http://unauthorized-site.example.com # Attempt to connect to an external site
          echo "Attempted malicious actions."

      - name: Verify eBPF Monitoring (Optional - Adapt based on kntrl capabilities)
        if: always()
        run: |
          echo "Checking for eBPF monitoring logs (adapt based on kntrl output)..."
          # Adapt this based on how kntrl reports events (e.g., log file, CLI command)
          # if [ -f /tmp/kntrl.out ]; then
          #   cat /tmp/kntrl.out | grep "malicious"
          # else
          #   echo "kntrl log file not found."
          # fi
          echo "Verification of eBPF monitoring complete (check logs for details)."