name: Kntrl Test Workflow

on:
  push:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test-kntrl:
    runs-on: epbfrunner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kntrl agent
        run: |
          echo "Setting up kntrl agent..."
          sudo docker run -d --privileged \
            --pid=host \
            --network=host \
            --cgroupns=host \
            --volume=/sys/kernel/debug:/sys/kernel/debug:ro \
            --volume /tmp:/tmp \
            --name kntrl-agent \
            docker.io/kondukto/kntrl:0.1.3 \
            --mode=monitor \
            --allowed-hosts=github.com,api.github.com,docker.io \
            --allow-local-ranges=true \
            --verbose

      - name: Wait for kntrl to initialize
        run: sleep 5

      - name: Verify kntrl setup
        run: |
          echo "Verifying kntrl is running..."
          docker ps | grep kntrl
          if [ -f /tmp/kntrl.log ]; then
            echo "✅ kntrl log file exists:"
            tail -n 10 /tmp/kntrl.log
          else
            echo "⚠️ kntrl log file not found, checking for alternatives..."
            ls -la /tmp/kntrl*
          fi

      - name: Run security test operations
        run: |
          echo "Running test operations to verify kntrl functionality..."
          # Test a legitimate operation
          echo "Testing legitimate operation - curl to github.com"
          curl -s https://github.com > /dev/null && echo "✅ Legitimate connection succeeded" || echo "❌ Failed"
          
          # Test a blocked operation
          echo "Testing blocked operation - curl to unauthorized domain"
          curl -m 5 -s http://example.org > /dev/null && echo "❌ Unauthorized connection succeeded" || echo "✅ Blocked as expected"

      - name: Check kntrl logs
        if: always()
        run: |
          echo "Checking kntrl logs after test operations..."
          if [ -f /tmp/kntrl.log ]; then
            echo "====== Last 20 lines of kntrl log ======"
            tail -n 20 /tmp/kntrl.log
          else
            echo "No kntrl.log found, checking docker logs:"
            docker logs kntrl-agent | tail -n 20
          fi

      - name: Cleanup
        if: always()
        run: |
          echo "Stopping kntrl agent..."
          docker stop kntrl-agent
          docker rm kntrl-agent