name: Financial Reporting Service

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3

      - name: Check Environment
        run: |
          echo "Checking kernel version:"
          uname -r
          echo "Checking system architecture:"
          uname -m
          echo "Checking Docker availability:"
          docker --version || echo "Docker not available"

      - name: Increase MEMLOCK limit
        run: |
          # Increase the memlock limit for the current session
          sudo sh -c "ulimit -l unlimited"
          # Check current limits
          ulimit -a

      - name: Start kntrl agent (Docker approach)
        run: |
          echo "Starting kntrl agent in monitor mode using Docker..."
          # List available docker images for kondukto/kntrl
          echo "Available kondukto/kntrl images:"
          sudo docker search kondukto/kntrl
          
          # Try to pull the 0.1.3 image
          echo "Attempting to pull kondukto/kntrl:0.1.3"
          if sudo docker pull kondukto/kntrl:0.1.3; then
            KNTRL_IMAGE="kondukto/kntrl:0.1.3"
            echo "Successfully pulled 0.1.3 image"
          else
            echo "Failed to pull 0.1.3 image, falling back to 0.1.2"
            sudo docker pull kondukto/kntrl:0.1.2
            KNTRL_IMAGE="kondukto/kntrl:0.1.2"
          fi
          
          # Run kntrl in monitor mode
          sudo docker run --privileged \
            --pid=host \
            --network=host \
            --cgroupns=host \
            --volume=/sys/kernel/debug:/sys/kernel/debug:ro \
            --volume /tmp:/tmp \
            --security-opt seccomp=unconfined \
            --rm $KNTRL_IMAGE \
            run --mode=monitor --allowed-hosts=kondukto.io,${{ env.GITHUB_ACTIONS_URL }} --allow-local-ranges=true &
          
          # Wait to ensure kntrl has time to start
          sleep 5
          echo "kntrl agent started in background via Docker."

      - name: Secured Build
        run: |
          echo "Secure financial reporting service build on this runner"
          hostname
          env
          ls -la

  malicious-build:
    runs-on: ebpf-runners-cicd
    steps:
      - uses: actions/checkout@v3

      - name: Check Environment
        run: |
          echo "Checking kernel version:"
          uname -r
          echo "Checking system architecture:"
          uname -m

      - name: Increase MEMLOCK limit
        run: |
          # Increase the memlock limit for the current session
          sudo sh -c "ulimit -l unlimited"
          # Check current limits
          ulimit -a

      - name: Start kntrl agent (Docker approach - Prevent Mode)
        run: |
          echo "Starting kntrl agent in prevent mode using Docker..."
          # Try to pull the 0.1.3 image
          echo "Attempting to pull kondukto/kntrl:0.1.3"
          if sudo docker pull kondukto/kntrl:0.1.3; then
            KNTRL_IMAGE="kondukto/kntrl:0.1.3"
            echo "Successfully pulled 0.1.3 image"
          else
            echo "Failed to pull 0.1.3 image, falling back to 0.1.2"
            sudo docker pull kondukto/kntrl:0.1.2
            KNTRL_IMAGE="kondukto/kntrl:0.1.2"
          fi
          
          # Run kntrl in prevent/trace mode
          sudo docker run --privileged \
            --pid=host \
            --network=host \
            --cgroupns=host \
            --volume=/sys/kernel/debug:/sys/kernel/debug:ro \
            --volume /tmp:/tmp \
            --security-opt seccomp=unconfined \
            --rm $KNTRL_IMAGE \
            run --mode=trace --allowed-hosts=kondukto.io,${{ env.GITHUB_ACTIONS_URL }} --allow-local-ranges=true &
          
          # Wait to ensure kntrl has time to start
          sleep 5
          echo "kntrl agent started in background with prevention enabled."

      - name: Simulate Malicious Actions
        run: |
          echo "Simulating malicious build trying to gain access..."
          hostname
          env
          ls -la /etc/shadow # Attempt to access a sensitive file
          mkdir /tmp/evil_dir
          echo "Malicious file created" > /tmp/evil_dir/malicious.txt
          curl -m 10 http://unauthorized-site.example.com # Attempt to connect to an external site
          echo "Attempted malicious actions."

      - name: Check kntrl Logs
        if: always()
        run: |
          echo "Checking kntrl logs..."
          if [ -f /tmp/kntrl.out ]; then
            cat /tmp/kntrl.out
          else
            echo "kntrl log file not found."
            echo "Trying to find logs from kntrl container:"
            sudo docker ps -a | grep kntrl
          fi