name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, kubernetes, harphies]
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: echo "Hello from containerized job"